#!/bin/bash
HOOK_NAMES="applypatch-msg pre-applypatch post-applypatch pre-commit prepare-commit-msg commit-msg post-commit pre-rebase post-checkout post-merge pre-receive update post-receive post-update pre-auto-gc"
REPO_HOOK_DIR=$(git rev-parse --show-toplevel)/.git/hooks
LOCAL_HOOK_DIR=$(git rev-parse --show-toplevel)/hooks

for hook in $HOOK_NAMES; do
    # If the hook already exists, is executable, and is not a symlink
    if [ ! -h $REPO_HOOK_DIR/$hook -a -x $REPO_HOOK_DIR/$hook ]; then
        mv $REPO_HOOK_DIR/$hook $REPO_HOOK_DIR/$hook.local
    fi
    # create the symlink, overwriting the file if it exists
    # probably the only way this would happen is if you're using an old version of git
    # -- back when the sample hooks were not executable, instead of being named ____.sample
    ln -s -f $LOCAL_HOOK_DIR/hooks-wrapper $REPO_HOOK_DIR/$hook
done
